name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Setup Python Environment for django project
              uses: actions/setup-python@v2
              with:
                python-version: 3.12
                architecture: x64
            
            - name: Checkout repository
              uses: actions/checkout@v3


            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name : Run Django Project
              run: |
                    python manage.py runserver
                    
                

            
